# Generated by Django 4.2.8 on 2023-12-04 19:02

from django.db import migrations, models
import hashid_field.field
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    hashid_field.field.BigHashidAutoField(
                        alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        auto_created=True,
                        min_length=13,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                (
                    "full_image",
                    models.ImageField(blank=True, null=True, upload_to="banners"),
                ),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
            },
        ),
    ]
