# Generated by Django 4.2.8 on 2023-12-04 19:02

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("df_banners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerVideo",
            fields=[
                (
                    "id",
                    hashid_field.field.BigHashidAutoField(
                        alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        auto_created=True,
                        min_length=13,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="banners/videos")),
                (
                    "banner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="df_banners.banner",
                    ),
                ),
            ],
        ),
    ]
